services:
  # Backend API Service
  - type: web
    name: college-cash-swap-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://college-cash-swap-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: college-cash-swap-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
